### ISSUE TITLE
can't make changes to the settings anymore

### ISSUE THREAD

**Issue by ak-hash** [glutanimate/review-heatmap#103]
#### Problem description

*trying to change the color of heatmap and i get an error ... pasted the entire error message below. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-17 19:13:48
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/AmanKalra/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_basic.py", line 93, in accept
    self._onAccept()
  File "/Users/AmanKalra/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "/Users/AmanKalra/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 216, in save
    saver(self._config[name])
  File "/Users/AmanKalra/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki/config.py", line 64, in __setitem__
  File "anki/config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

```
    
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.16
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-12-17 19:13:48
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2020-07-25T05:19, 'None', mod]
    Add a tag to notes with missing media ['2027876532', 2019-10-31T16:49, 'None', '']
    AddonBackup ['162231225', 2019-09-09T02:28, 'None', '']
    Advanced Browser ['874215009', 2020-11-08T03:03, 'None', '']
    Anki Simulator ['817108664', 2020-07-21T07:17, 'None', '']
    BetterSearch ['1052724801', 2020-10-25T13:49, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T13:01, 'None', '']
    Deck Counts NowLater ['1836212767', 2020-09-09T08:33, 'None', '']
    Deck Stats ['1421528223', 2020-09-02T12:45, 'None', '']
    Fastbar- with nightmode support ['46611790', 2020-03-20T07:34, 'None', '']
    Frozen Fields ['516643804', 2020-05-11T14:30, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-05-11T14:32, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-05-11T14:30, 'None', '']
    ImageResizer ['1214357311', 2019-10-15T19:16, 'None', '']
    Increase autosave frequency ['786971082', 2019-09-09T02:21, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2020-09-26T13:33, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-05-11T14:30, 'None', '']
    More Overview Stats ['2116130837', 2020-05-11T14:30, 'None', '']
    Progress Bar ['2091361802', 2019-06-18T17:29, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-05-11T14:31, 'None', '']
    Quick  Easy ['1834460432', 2019-10-22T21:42, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T09:17, 'None', '']
    Review Heatmap ['review_heatmap', 2018-10-28T15:06, 'None', '']
    Study Logger ['1919929679', 2019-10-23T21:07, 'None', '']
    Symbols As You Type ['2040501954', 2020-04-30T07:32, 'None', '']
    Symbols ['1461102936', 2019-09-09T02:11, 'None', mod]
    The KING of Button Add-ons ['374005964', 2020-04-17T15:33, 'None', mod]
    True Retention ['613684242', 2017-11-19T12:43, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-08-29T11:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1052724801 1214357311 1237621971 1374772155 1421528223 1461102936 1556734708 162231225 1834460432 1836212767 1919929679 1949865265 1988760596 2027876532 2040501954 2091361802 2116130837 266436365 300884351 374005964 46611790 516643804 594329229 613684242 786971082 817108664 864545277 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by k-kirill** [comment]
I had a similar error and reinstalling the add-on using the latest beta from the link mentioned at https://ankiweb.net/shared/info/1771074083 has helped me.

**Comment by ak-hash** [comment]
> I had a similar error and reinstalling the add-on using the latest beta from the link mentioned at https://ankiweb.net/shared/info/1771074083 has helped me.

worked!!! thank you so much!!
