### ISSUE TITLE
Heatmap color getting lighter as more reviews are done instead of darker 

### ISSUE THREAD

**Issue by Dualbladeguy** [glutanimate/review-heatmap#119]
#### Problem description

i have been doing anki for 7 days consecutively, but the most intense color (dark red) on heat map only had 17 cards reviewed, while the lightest color (whitish yellow) on the heatmap has 124 cards reviewed. My settings is "flame". is this normal? Is the color intensity based on the percentage of daily new cards done? or is it just based on the amount of cards reviewed?

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```    
    Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.7
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-05-29 22:13:26
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2021-05-03T14:27, 'None', '']
    Add Hyperlink ['318752047', 2020-07-29T22:37, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2020-09-20T13:50, 'None', mod]
    Advanced Browser ['874215009', 2020-10-04T05:40, 'None', mod]
    Anki Palace Butler ['butler', 2020-11-14T22:33, 'None', mod]
    Anki Simulator ['817108664', 2021-02-21T16:44, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T02:20, 'v1.1.3', '']
    Batch Editing ['291119185', 2019-09-19T19:04, 'None', '']
    BetterSearch ['1052724801', 2020-10-25T21:49, 'None', mod]
    Browser Resizer ['1435775540', 2020-09-08T04:04, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2021-05-27T18:47, 'None', mod]
    Card browser List only one card per note ['797076357', 2020-08-11T06:23, 'None', mod]
    Clickable Tags v20 Anki 2120 support ['1739176371', 2020-03-13T15:25, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-03-02T04:14, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2021-04-02T18:21, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2021-02-18T02:36, 'None', mod]
    Customize Sidebar ['1988760596', 2020-01-16T23:12, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2020-12-17T09:42, 'None', mod]
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-19T02:29, 'None', mod]
    Fastbar- with nightmode support ['46611790', 2021-05-19T02:50, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T05:12, 'None', '']
    Hierarchical Tags 2 ['594329229', 2021-03-07T03:25, 'None', '']
    High Yield Tags ['1918380616', 2020-06-30T22:35, 'None', mod]
    Highlight Search Results in the Browser ['225180905', 2021-03-10T18:06, 'None', '']
    Hint Hotkeys ['1844908621', 2019-02-26T19:58, 'None', '']
    Image Editor ['307397307', 2021-02-24T10:41, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    Image Style Editor ['1593969147', 2020-12-17T14:06, 'None', mod]
    ImageResizer ['1214357311', 2021-04-10T18:15, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2020-12-28T23:40, 'None', '']
    Legacy ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-20T06:27, 'None', mod]
    More Decks Stats and Time Left ['1556734708', 2021-01-27T10:09, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-02-05T18:35, 'None', mod]
    Pop-up Dictionary beta ['153625306', 2019-03-23T18:32, 'None', '']
    Puppy Reinforcement ['1722658993', 2020-03-02T21:23, 'None', '']
    Quick Colour Changing ['2491935955', 2019-03-03T03:26, 'None', mod]
    Refocus Card when Reviewing 21 ['1642550423', 2019-03-04T19:20, 'None', '']
    Resize images in editor ['1103084694', 2020-08-02T15:04, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Special Fields ['1102281552', 2021-02-13T23:52, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail/good ['1046608507', 2019-06-02T11:11, 'None', '']
    Straight Reward ['957961234', 2020-09-16T16:45, 'None', mod]
    Symbols As You Type ['2040501954', 2021-03-22T03:17, 'None', '']
    Symbols ['1461102936', 2019-04-23T15:37, 'None', mod]
    The KING of Button Add-ons ['374005964', 2020-04-18T00:33, 'None', '']
    The KING of Study Timers ['907028815', 2020-08-09T02:37, 'None', mod]
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-08-29T20:23, 'None', mod]
    Wrapper meta-addon ['396502676', 2021-05-19T03:10, 'None', mod]
    Ze Add Note Id ['886709118', 2020-07-30T18:12, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2020-05-08T15:16, 'None', '']
    put ALL due learning cards first modified v2 support ['1807121582', 2019-11-24T20:20, 'None', '']
    rebuild allempty all filtered decks enhanced fork ['104518886', 2020-10-08T16:53, 'None', '']
    when is next learning card due today due ['563204849', 2020-09-13T15:51, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    104518886 1046608507 1052724801 1102281552 1103084694 1135507717 1210908941 1214357311 1374772155 1435775540 1461102936 153625306 1556734708 1593969147 1642550423 1722658993 1739176371 1807121582 1844908621 1918380616 1949865265 1988760596 2040501954 225180905 24411424 2491935955 291119185 307397307 318752047 323586997 374005964 385888438 396502676 46611790 516643804 538879081 561945101 563204849 594329229 738807903 744725736 797076357 817108664 831846358 861263371 864545277 874215009 886709118 907028815 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-23T23:03, 'None', '']
    Extended Card Stats During Review ['1008566916', 2019-03-02T04:14, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T13:57, 'None', mod]
    Load Balanced Scheduler ['208879074', 2019-07-24T04:37, 'None', '']
    Mini Format Pack ['295889520', 2019-03-02T04:13, 'None', '']
    Progress Bar ['2091361802', 2019-03-03T03:27, 'None', '']
    Reset Ease ['947935257', 2020-12-27T15:59, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T20:52, 'None', mod]
    deck and card info sidebar during review ['673114053', 2020-09-20T14:17, 'None', '']


```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by Dualbladeguy** [comment]
Sorry please ignore the above, I just found a post regarding this.  It is due to turning on nightmode inverts the colors.

**Comment by stegatxins0** [comment]
Try [my fork of review heatmap](https://github.com/stegatxins0/review-heatmap/releases/tag/v1.0.0-beta.2). Colors is not inverted in night mode.

![](https://i.imgur.com/Kbc6Nn7.jpg)

**Comment by glutanimate** [comment]
(and thanks for providing a workaround @stegatxins0 !)

**Comment by deev1207** [comment]
> Try [my fork of review heatmap](https://github.com/stegatxins0/review-heatmap/releases/tag/v1.0.0-beta.2). Colors is not inverted in night mode.

This error shows while opening anki with your addon. worked fine until recently.
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-06-27 23:21:54

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "C:\Users\Deev\AppData\Roaming\Anki2\addons21\review_heatmap\views.py", line 74, in initializeHotkey
    hotkey = config["profile"]["hotkeys"]["toggle"]
KeyError: 'toggle'

**Comment by ItsCheif** [comment]
> Try [my fork of review heatmap](https://github.com/stegatxins0/review-heatmap/releases/tag/v1.0.0-beta.2). Colors is not inverted in night mode.

This fork no longer works on Version 23.12.1 of Anki, anybody have any solutions to this problem?
