### ISSUE TITLE
Set a history beginning date rather than a history limit in days before the present

### ISSUE THREAD

**Issue by TimotheeChauvin** [glutanimate/review-heatmap#14]
If you've recently begun using Anki with a completely new determination (which I think happens to many people at some point) and have a history of low activity before that day, you may wish to forget the previous period and set a date as the beginning of history. This way, the 'daily average' and 'days learned' would make more sense. (if you want to have this feature, you currently have to change the history limit every day)
If this is an issue because of performance, you can set both a history beginning date and a history limit.

**Comment by glutanimate** [comment]
Thanks for the great suggestion! The rolling time scope of the add-on has been bothering me, too, lately. 

This shouldn't be too difficult to implement, so I've added it to my personal to-do list.

**Comment by glutanimate** [comment]
Implemented with c7480bc1dcb0a02e93cb697551ea80bcb8e160bf
