### ISSUE TITLE
Option to exclude deleted cards from review history

### ISSUE THREAD

**Issue by glutanimate** [glutanimate/review-heatmap#15]
As suggested by Fin (https://anki.tenderapp.com/discussions/add-ons/8707-review-heatmap-official-thread#comment_44946934).

Could help address issues with old revlog entries (cf. https://anki.tenderapp.com/discussions/add-ons/8707-review-heatmap-official-thread/page/1#comment_44926664)

**Comment by glutanimate** [comment]
See https://github.com/dae/anki/blob/master/anki/stats.py#L900-L904 for anAnki's implementation of revlog limits.

**Comment by Clement-Jean** [comment]
I would like to help, can we discuss about it ?

**Comment by glutanimate** [comment]
Hi Clement-Jean,

I've started working on this recently as part of the v0.7.0 release, but completely forgot to update the issue status. Sorry about that! I really do appreciate your offer, though!

**Comment by glutanimate** [comment]
Implemented with dc739cd56f769a686a334828799b2fb6595a0ab3

P.S.: Clement, sorry for not getting back to your email, yet. With my studies starting back up I've had very little time to deal with my inbox. I will try to message you back when I can.
