### ISSUE TITLE
Scroll button did not work correctly

### ISSUE THREAD

**Issue by HTLife** [glutanimate/review-heatmap#16]
In month mode, when you press left button beside 'T' button, the history is shown.
However, if you press the right button, it will not scroll back to current date.

**Comment by glutanimate** [comment]
Hey @HTLife,

Thanks for the bug report, and sorry for the delayed response. I've just pushed out a [new beta release](https://github.com/glutanimate/review-heatmap/releases) which should address this issue (among other bugs). If you get the chance please do give it a try and let me know if it fixes the scroll navigation for you.

**Comment by HTLife** [comment]
Cool, you add lots of function and fix this bug on v0.7.0.  Nice work!

**Comment by glutanimate** [comment]
Awesome! Glad to hear that everything is working now :)
