### ISSUE TITLE
Future cube mouseover text reads "NaN cards due on . . . "

### ISSUE THREAD

**Issue by onebigchildren** [glutanimate/review-heatmap#165]
#### Problem description

Hi! Firstly thank you so much for the amazeballs addon :D

A future cube's mouseover text reads "NaN cards due on . . . " where I have 1109 due on that date.
Last time I checked it showed 700 fine, so my guess (& from reading past reports) is perhaps 1k tipping it over into the NaN area?
[Imgur Link
](https://i.imgur.com/7kvFVdW.png)

The heatmap keeps me going! Thank you >:)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.16
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-06-21 02:17:33

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi, thanks for the report (and for the kind words!). This should be fixed in the latest version which you can download on AnkiWeb: https://ankiweb.net/shared/info/1771074083

**Comment by glutanimate** [comment]
Actually, nvm, I haven’t pushed v1.0.1 to AnkiWeb yet, but it should hopefully be up soon. Until then you can also track progress on this via https://github.com/glutanimate/review-heatmap/issues/30

**Comment by glutanimate** [comment]
OK, the update should be live now
