### ISSUE TITLE
Heat Map not showing Heat map icon at the bottom. See attached picture..

### ISSUE THREAD

**Issue by z3n-k3rn3l** [Glutanimate/review-heatmap#168]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
As you can see from below image the heat map icons/pictures is not displaying..

![image](https://user-images.githubusercontent.com/75212700/177906551-94062e47-4ddf-4f50-b859-6395ac8681bb.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-07-08 08:08:00
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Heatmap ['1722241614', 2019-08-18T21:05, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T12:45, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-07T07:01, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 1463041493 1722241614
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    


```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hey, thanks for the report.

It looks like you have an old unofficial version of the add-on installed. From Anki's main screen, please head to *Tools* → *Add-ons*, uninstall "Heatmap", and then install the official version of Review Heatmap from here: https://ankiweb.net/shared/info/1771074083

After that, the add-on should show up again.

**Comment by z3n-k3rn3l** [comment]
Thanks glutanimate. The issue is solved..
