### ISSUE TITLE
After not using anki for a couple of months, heatmap isnt showing up, shows images instead?

### ISSUE THREAD

**Issue by Divincloud03** [Glutanimate/review-heatmap#171]
Hi! 
Ive found your add on to be super helpful :) unfortunately im having this issue, could you help me?
<img width="683" alt="image" src="https://user-images.githubusercontent.com/111133570/184368570-adf0ce19-12e2-4252-a056-e6c51fc12ba8.png">

**Comment by glutanimate** [comment]
Heya, thanks for reaching out. It looks like you're using an older version of the add-on. Deleting the one you currently have installed under Tools → Add-ons (could also be called "Heatmap", or "ReviewHeatmap"), and then installing the latest one from AnkiWeb should fix things: https://ankiweb.net/shared/info/1771074083

Hope that helps!
