### ISSUE TITLE
manually set due date not counted

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Glutanimate/review-heatmap#174]
#### Problem description

If I manually set the due date for a card while reviewing, this review is not included in review-heatmap.
While I'm reviewing my cards, sometimes the Anki suggested due date is not proper and I want to manually set one. For example, after I click the "Show Answer" button, Anki displays this:
```
 <10m        <15m        1d         2d
┌───────┐   ┌──────┐   ┌──────┐   ┌──────┐
│ Again │   │ Hard │   │ Good │   │ Easy │
└───────┘   └──────┘   └──────┘   └──────┘
```
In this case, I want the due date to be 5-10 days. So I press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>d</kbd> and type `5-10`, then press <kbd>Enter</kbd>. I have reviewed this card, but it will not be counted by review-heatmap.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-09-06 07:56:00
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', '']
    Add Hyperlink ['318752047', 2022-05-23T21:16, 'None', '']
    Advanced Browser ['874215009', 2022-01-31T07:07, 'None', mod]
    Advanced Review Bottom Bar ['1136455830', 2022-08-18T11:38, 'None', mod]
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T18:41, 'None', '']
    Highlight Color Shortcut ['1178291236', 2021-04-02T00:42, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-11T01:06, 'None', '']
    Mini Format Pack ['295889520', 2018-07-25T01:45, 'None', mod]
    More Decks Stats and Time Left ['1556734708', 2022-05-20T18:23, 'None', mod]
    Opening the same window multiple time ['354407385', 2020-05-16T08:59, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2022-03-13T18:51, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1135507717 1136455830 1178291236 1556734708 1771074083 225180905 295889520 318752047 354407385 805891399 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2022-07-15T04:15, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T11:10, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, thanks for the detailed feedback! You can tweak this behavior in RH's options (by default, manual reschedule events will be excluded from the activity report).
