### ISSUE TITLE
Heatmap is one day behind?

### ISSUE THREAD

**Issue by nicrodwell** [Glutanimate/review-heatmap#175]
#### Problem description

Heat map displays the current date as yesterday and also says i have no reviews due on the current (true) date.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 12.4
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-02 12:00:58
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Simulator ['817108664', 2021-08-08T05:24, 'None', '']
    Edit Field During Review ['1020366288', 2022-08-30T05:38, 'None', '']
    Mini Format Pack ['295889520', 2018-07-25T03:45, 'None', '']
    Postpone cards review ['1152543397', 2021-01-29T10:20, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T11:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1152543397 1771074083 295889520 817108664
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
<img width="1699" alt="Screen Shot 2022-10-02 at 12 12 46 pm" src="https://user-images.githubusercontent.com/114840306/193433795-2b10d44d-2cf3-4d52-9c90-f92a8dbb0fdd.png">

```

```
<img width="1709" alt="Screen Shot 2022-10-02 at 12 12 06 pm" src="https://user-images.githubusercontent.com/114840306/193433786-28bb5c1f-3d4f-4006-8d7c-d199bf246277.png">

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by nicrodwell** [comment]
Update, now on the correct day. But it just skipped yesterday and double counted the day before? Not a biggie but its not as pretty anymore ;(

**Comment by glutanimate** [comment]
Thanks for the detailed report! I was hoping v1.0.0 would have addressed the DST problems, but it looks like they persist. Will look into it. Please feel free to track progress on the fix in #128 (closing this issue in favor of the older report).
