### ISSUE TITLE
The graph shows phantom reviews

### ISSUE THREAD

**Issue by Jylme** [glutanimate/review-heatmap#18]
The graph shows that I did some reviews on Monday, but I did not. I did some on Sunday, about 9:30 p.m.

![aa](https://user-images.githubusercontent.com/39779361/41207013-20792586-6d0e-11e8-80a6-8287de21ab62.png)

**Comment by glutanimate** [comment]
Hi Jylme,

Thanks for the report! This is likely the same issue as #23. Let's move the discussion there for now as I've already compiled quite a bit of troubleshooting information there with another user experiencing this as well.
