### ISSUE TITLE
Broken images after Anki update

### ISSUE THREAD

**Issue by dharrison4** [Glutanimate/review-heatmap#184]
#### Problem description

Anki was updated yesterday to 2.1.63 (Qt6). Heatmap is now 5 broken image icons, vertically arranged. Screenshot at the bottom.

#### Checklist

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki. 
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. 
   - [X] add-on description
     - The [negative reviewer on anki add-on page listing](https://ankiweb.net/shared/info/1771074083) is probably talking about this error.
   - [X] documentation
   - [X] README.
 
#### 

#### Information about your Anki set-up

```
    
    Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.19044
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-05-15 12:11:16
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Review Heatmap ['review_heatmap', 2020-04-30T07:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2023-04-11T11:20, 'None', '']
    Batch Editing ['291119185', 2019-06-02T12:47, 'None', '']
    Button Colours Good Again ['2494384865', 2022-09-27T04:18, 'None', '']
    Countdown To Events and Exams ['1143540799', 2022-06-27T05:50, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2023-04-18T19:19, 'None', mod]
    Deadline2 ['723639202', 2021-05-01T22:45, 'None', mod]
    Deck name in title 21 ['699175524', 2019-05-31T19:05, 'None', '']
    Edit Field During Review Cloze ['385888438', 2022-06-27T03:48, '6.13', mod]
    HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T21:35, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T01:15, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T11:45, 'None', '']
    Quizlet to Anki 21 Importer with audio support ['1362209126', 2023-04-05T20:35, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-06T19:31, 'None', mod]

```

![image](https://github.com/glutanimate/review-heatmap/assets/6942985/e726137d-16e3-4dc9-9859-6891e2c081d8)

#### Error message (if any)

`No error messages`

```python

```

**Comment by glutanimate** [comment]
Hey @dharrison27, thanks for the detailed report! It looks like you have an older version of the add-on installed. Please delete the one you currently have installed and download the latest release from [AnkiWeb](https://ankiweb.net/shared/info/1771074083). That should fix the missing heatmap :)

**Comment by dharrison4** [comment]
> It looks like you have an older version of the add-on installed. Please delete the one you currently have installed and download the latest release from [AnkiWeb](https://ankiweb.net/shared/info/1771074083). That should fix the missing heatmap :)

That's weird because it was set always to update, as shown by the line `last update check: 2023-05-15 12:11:16`. 

I deleted the add-on and re-added it, making sure it was the same one as before, and now it works 🤷‍♂️ 
(same Anki version, without other add-ons enabled)
