### ISSUE TITLE
Offer .ankiaddon file for v1.0

### ISSUE THREAD

**Issue by afonsoalbrecht** [Glutanimate/review-heatmap#185]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### Problem case

I can't get and install the add-on directly from the ankiwe, i keep getting the below error: 

`One or more errors occurred:  1771074083: Please check your internet connection. HTTPSConnectionPool(host='ankiweb.net', port=443): Max retries exceeded with url: /shared/download/1771074083?v=2.1&p=55 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`

#### Solution

By installing manually the .addonanki file, I'm able to avoid having this error.

**Comment by glutanimate** [comment]
Hi Alfonso,

AnkiWeb is now the main installation path for Review Heatmap and while I will likely add GitHub releases back in the future, I'm not sure yet when exactly. Having add-on builds available both via AnkiWeb and GitHub can be helpful, but can also be confusing to users, and AnkiWeb typically is the best way to install Anki add-ons (as e.g. it allows them to be kept up-to-date automatically)

However, for now, [here's the direct download link](https://github.com/glutanimate/temp-workspace/releases/download/0.0.1/review-heatmap-v1.0.1-qt5+qt6-ankiweb.ankiaddon) the the latest `.ankiaddon` file.

To perhaps help with the underlying error:

From the sounds of the error message, it seems like your Anki installation is having trouble connecting to AnkiWeb, so I would assume this is a problem that extends to other add-on downloads as well, and perhaps even syncing your flashcard data.

To resolve this, you could try updating Anki to the latest release (2.1.64 as of now). Recent updates have had some fixes in regards to SSL handling. Restarting Anki before attempting to download an add-on might also help.

Hope that helps :)

**Comment by afonsoalbrecht** [comment]
Brilliant! It's installed.

Yeah, I get the benefits of installing the add-on through AnkiWeb, but sometimes when you're using a work computer, you need to get special permission to download stuff. In those cases, just getting the latest release won't fix the issue.

Thanks a lot for sending the file!
