### ISSUE TITLE
The heatmap is missing in the Anki overview page (Anki 2.1.65)

### ISSUE THREAD

**Issue by ColinKennedy** [Glutanimate/review-heatmap#186]
#### Problem description

Overview heatmap missing on the latest Anki. I upgraded from Anki 2.1.60 to Ankit 2.1.65 and then Anki prompted me to update all plugins. I should've made a back up just in case but forgot and now review-heatmap seems to be broken. I can't get it to show again.

This is what I can see on the top-level Anki view, on-startup

![image](https://github.com/glutanimate/review-heatmap/assets/10103049/1ed2a73e-9610-4d06-ba94-b5d81f64beda)

If I click on an individual section, I can see review-heatmap there

![image](https://github.com/glutanimate/review-heatmap/assets/10103049/7eb7a3f7-8e3d-44d9-b221-b32afe9b0de6)

So the plugin works for individual / aggregate decks but not for the main Anki page, which is frustrating. A suggested fix would be appreciated.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.19045
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-07-15 06:26:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1051095155 1655992655 1771074083 278530045
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2023-06-18T04:39, 'None', '']
    Add note id ['1672832404', 2020-12-06T02:44, 'None', '']
    Advanced Browser ['874215009', 2023-07-01T12:55, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T11:46, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T12:24, 'None', '']
    Bulk Reading Generator Plus ['925924910', 2019-02-10T11:50, 'None', '']
    Deck Counts NowLater ['1836212767', 2020-09-09T08:33, 'None', '']
    Fastbar- with nightmode support ['46611790', 2023-06-27T04:47, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T00:15, 'None', '']
    Japanese Example Sentences ['2413435972', 2019-02-20T11:40, 'None', mod]
    Japanese Support ['3918629684', 2022-03-13T20:32, 'None', '']
    MeCab UniDic Japanese Dictionary ['13462835', 2019-08-18T06:09, 'None', '']
    MorphMan for Anki 21 ['900801631', 2023-01-10T12:01, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-06T18:31, 'None', mod]
    export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2022-04-12T08:17, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
C:\Users\korinkite>C:\Users\korinkite\AppData\Local\Programs\Anki\anki.exe

C:\Users\korinkite>Anki starting...
Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Qt info:

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name Anki
  *  browser-subprocess-path C:\Users\korinkite\AppData\Local\Programs\Anki\lib\PyQt6\Qt6\bin\QtWebEngineProcess.exe
  *  create-default-gl-context
  *  disable-es3-gl-context
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl desktop

Starting main loop...
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
```

**Comment by glutanimate** [comment]
Hi, thanks for the detailed report!

Could you please check if heatmap visibility is turned on for all screens in the add-on's settings? (under _Tools_ → _Review Heatmap Options_)

It should look like this by default:

![Screenshot_20230715_164837](https://github.com/glutanimate/review-heatmap/assets/5459332/73b0aa2a-1435-431f-a6ea-f424d398ec1c)

If the option is checked and the heatmap still does not show up, please draw up the options dialog again and try resetting the settings to the defaults by clicking on _Restore Defaults_ and then confirming with _OK_.

If neither of these work we'll have to dig a bit deeper since I can't reproduce the issue locally on 2.1.65.

**Comment by ColinKennedy** [comment]
You're completely right. I had forgotten there was a settings dialog separate from the plugin config. I've enabled it and it is now working as expected. Thank you! For the quick reply and for not shaming my silly mistake :)

**Comment by glutanimate** [comment]
Thanks for checking, happy it was just that! And no worries, always appreciate detailed bug reports like yours :)
