### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by absolutecelsius** [Glutanimate/review-heatmap#199]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

Hello. I just want to ask if the addon is still in development, since the last commit is 2 years ago. Thank you!

**Comment by glutanimate** [comment]
Hi there, yes, I've been working on a larger update to the add-on that should hopefully be ready soon.

**Comment by absolutecelsius** [comment]
Thank you so much for replying! I will close the issue.
