### ISSUE TITLE
Add support for tracking >365 days of progress

### ISSUE THREAD

**Issue by ceribik** [glutanimate/review-heatmap#20]
The addon currently does not track more than 365 days of progress. After a year, the progress stays at 365 consecutive days of reviews and progress is silently removed from the start, day by day.

It would be nice to support more days e.g. up to five years.

**Comment by glutanimate** [comment]
You can customize the period of time that the add-on tracks in the options menu. It supports any arbitrary number of days. You can also remove the limits by setting the values to -1.
