### ISSUE TITLE
forms4.py and forms5.py are missing

### ISSUE THREAD

**Issue by bmintz** [glutanimate/review-heatmap#22]
Hi there! I just wanted to run a copy of this add-on, but I noticed that two files are missing. They are imported here:
https://github.com/glutanimate/review-heatmap/blob/60cfb2510dc1f665bbd5d7d579f8839cf1005caa/src/review_heatmap/options.py#L24-L27

Are these generated from .ui files? If so, what command needs to be run to do that?

**Comment by glutanimate** [comment]
Hi, thanks for pointing this out!

Yes, these are generated from .ui files. I forgot to re-add the build tools after the last batch of commits. A makefile and UI build script is available now, so you can use that to build the latest version of the add-on. However, the master branch is currently in a transitional state, so there's no guarantee that the add-on will work properly (or will continue to do so over the next commits). 

If you'd just like to have a working 2.1 version of the add-on my advice would be to check out this commit: https://github.com/glutanimate/review-heatmap/tree/b668b00192428d6d954d870dfbe69b86a1964523
