### ISSUE TITLE
Small tweak that just looks more pleasing

### ISSUE THREAD

**Issue by MedAnki** [glutanimate/review-heatmap#24]
## Prerequisite checklist

* [Y] In case of a bug: Have you tried restarting Anki?
* [Y] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [Y] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [Y] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
so I would like to see this as default
<img width="863" alt="screen shot 2018-08-31 at 10 29 46 pm" src="https://user-images.githubusercontent.com/42865576/44926225-5fcbce00-ad6e-11e8-8a01-6ec7b0b1778c.png">
but I see this as default 
<img width="836" alt="screen shot 2018-08-31 at 10 29 35 pm" src="https://user-images.githubusercontent.com/42865576/44926241-69edcc80-ad6e-11e8-82b2-42d753825879.png">
and going back to the main deck page/restarting Anki will always show the 2nd screenshot instead of the first. I tried to play around with the setting options but since I am not coding literate I don't know anything about this. Its just a small tweak. looks pleasing to the eye.

[Be as specific as possible. Provide screenshots if you think they can help.]

## How can we reproduce the problem?

[What were you doing when the problem occurred?]

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproducible?:** [Can you reliably reproduce the issue by following the steps above?]

## Version information

**Anki**
Version 2.0.52
Qt 4.8.2 PyQt 4.9.4

[Please head to *Help* → *About Anki* and Paste the version string here, e.g.:]

[Version 2.0.47]
[Qt 4.8.1 PyQt 4.9.1]

**System**

- Operating system: Mac [Windows/macOS/Linux]
- Version: High Sierra 10.13.3 [e.g. 10, High Sierra, Ubuntu 18.04]

**Comment by glutanimate** [comment]
Agreed. I've recently implemented this in the dev build. It will ship with Review Heatmap's next AnkiWeb release.

**Comment by MedAnki** [comment]
Kudos!
