### ISSUE TITLE
Can't seem to install on Linux?

### ISSUE THREAD

**Issue by kyubae** [glutanimate/review-heatmap#28]
I seem to be having an issue installing the add on on Linux (Debian Testing)
Here's what happens when I try to install it via using the Addon code:
https://i.imgur.com/hP9cF3o.png
Is this an issue on my end or is there something that stops this  add on from working on the Linux version of Anki?

**Comment by Minoru** [comment]
You probably resolved this already, but in case you didn't: the version from ankiweb is only compatible with Anki 2.0, while Debian testing ships 2.1. There are beta versions of this addon that are compatible with 2.1. Go [to the changelog](https://github.com/glutanimate/review-heatmap/blob/master/CHANGELOG.md), pick a version, click "Download", and follow the installation instructions there. I just installed this addon that way on Debian testing, and confirm that it works.

**Comment by kyubae** [comment]
Thanks that did fix it!

**Comment by glutanimate** [comment]
@Minoru Thanks for chiming in! Happy to see that this was resolved. Enjoy using RH, @kyubae :)
