### ISSUE TITLE
Cards Due NaN for counts >1000

### ISSUE THREAD

**Issue by chkmte** [glutanimate/review-heatmap#30]
If I have over 1,000 cards due for a future day hovering the cursor over that day says NaN. If I reviewed 1,000+ today or in the past it shows the exact number, but not for future counts. If I click on the next day's box it will pull up all the due cards, but the hover feature is not working.

**Comment by Z1839** [comment]
I have the same issue.

**Comment by glutanimate** [comment]
Thanks for the report, guys. I'll try to look into this soon.

**Comment by TheLastSage** [comment]
hey there @glutanimate just bumping this, as a few of my friends have run into it as well!

**Comment by ybn1996** [comment]
Hello, I have run into this issue as well. Wanted to bump this for visibility. Thank you for your work!

**Comment by abschectman** [comment]
@glutanimate My partner has also been experiencing this issue, just commenting for visibility.  Thanks so much for all your work

**Comment by glutanimate** [comment]
Thanks for the pings, guys. Will see if this is easily fixable. It's definitely been an issue for way too long.

**Comment by glutanimate** [comment]
OK, just pushed a change that should address the `NaN` tooltip issue. It should land in the next update which you should get an automatic notification for if you install the recently uploaded [AnkiWeb version](https://ankiweb.net/shared/info/1771074083) of the add-on (will require Anki 2.1.49+).

Thanks again for your patience guys. I guess better late than never :sweat_smile:
