### ISSUE TITLE
Anki 2.1 and 2.0 show different streaks

### ISSUE THREAD

**Issue by MrPiethon** [glutanimate/review-heatmap#31]
#### Problem description or Feature request

If I open up Anki 2.0 on my desktop it shows my actual streak of 54 days. If I sync and open it up on my laptop that is running Anki 2.1, it shows a streak of 4 days. It is showing that I have no studied and cards on certain days, but in fact I have. I am expecting on Anki 2.1 to show the same streak of 54 days.

#### Checklist
 - [ x ] I restarted Anki to see if it helps
 - [ x ] I verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x ] I verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x ] I tried to disable other add-ons to see if there are any interactions present
 - [ x ] I checked if anyone reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

```
Anki Settings (both computers)
- new day starts 12 hours after midnight
```

```
Version 2.1.8 (71e0c880)
Qt 5.9.7 PyQt 5.9
```

```
OS: Windows 10, Latest
```

[https://i.gyazo.com/468157f901849ea78e8d115872813b90.png](url)
 

</details>

#### Error message (if any)

<details>

*If you got an error message, please copy and paste it below:*

```python"
[paste your error message in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by MrPiethon** [comment]
Additional steps taken:
- Deleted all the decks, but previous streak/study information is still visible
- Tried deleting the addon in addition to the decks, and then reinstall addon -> previous information still retained
- Tried exporting the deck from anki 2.0 with correct streak, and importing it into 2.1 -> still wrong streak

**Comment by mavric1298** [comment]
I'm seeing similar issues with number of cards not being correct - 2.0 is showing the correct count but in 2.1 it's off - both in looking at built in stats, and by searching using "rated:1" the counts are quite a bit different.  I think it might have to do with new day start time but not sure

**Comment by MrPiethon** [comment]
I'm not sure if day light savings had a part in it, but I fixed it by going back an hour. Everything seems to be working right now.
