### ISSUE TITLE
How to install the 2.1 addon

### ISSUE THREAD

**Issue by Fandekasp** [glutanimate/review-heatmap#32]
Related issue: #6

Problem: review-heatmap doesn't appear in https://ankiweb.net/shared/addons/2.1.
Trying to install the 2.0 version fails.

I'm a bit confused, because other issues like #9 and #31 imply that other users are using this add-on on 2.1, yet I haven't seen the release statement.
If review-heatmap can indeed be used with v2.1, would you mind pointing me to the installation steps? 

Thank you for making this addon.

**Comment by jeffreykxiao** [comment]
You can download it here:
https://github.com/glutanimate/review-heatmap/blob/master/CHANGELOG.md

It's linked in an in-text hyperlink on the page for 2.0 https://ankiweb.net/shared/info/1771074083

Good luck!

**Comment by Fandekasp** [comment]
lol. End of the week, sorry about that <3
