### ISSUE TITLE
Add-on considers day 1 and day 2 as single day while calculating daily average. Everything else works fine.

### ISSUE THREAD

**Issue by adix03** [glutanimate/review-heatmap#40]
#### Problem description or Feature request

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following sentences apply to you. Feel free to disregard some of these if you're posting a feature request rather than a bug report.*

 - [ ] I restarted Anki to see if it helps
 - [ ] I verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I tried to disable other add-ons to see if there are any interactions present
 - [ ] I checked if anyone reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version:
Qt:
```

*Please fill in your OS details (Linux/Mac/Windows, which version):*

```
OS:
```

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
 

</details>

#### Error message (if any)

<details>

*If you got an error message, please copy and paste it below:*

```python"
[paste your error message in here if you got any; otherwise feel free to remove this part]
```

</details>

**Comment by miallo** [comment]
I observed the same issue:
I had Anki for two days and the day before yesterday I learned 144 and yesterday 177 cards and the `Daily average` is displayed as 321 instead of 160 (or if it would include today it could also be 107). Afterwards: Today I learned a single card and now the average is shown as 161, so this rather looks like an off-by-one-error to me ;)

**Comment by hillnj26** [comment]
Hi. Was this over resolved? My heatmap is having the same issue.

**Comment by glutanimate** [comment]
Hey guys!

Thanks for the reports (and sorry for taking way too long to respond). I just pushed out a [new beta update for Review Heatmap](https://github.com/glutanimate/review-heatmap/releases/v1.0.0-beta.1) which should address the issue. If you can, would you mind giving it a try and letting me know if it fixes things for you? I would really appreciate that. Thanks again!

**Comment by hillnj26** [comment]
Hi!

This fixed the issue for me. I deleted the old heatmap addon, installed this, and it worked perfectly. I tested by switching around the "Ignore data before" date and it calculated it correctly each time. Thank you for everything you do!

**Comment by glutanimate** [comment]
Glad to hear that, @hillnj26 ! Thanks for taking the time to test the changes, and thanks for your kind words :)

Closing this issue report as resolved then.
