### ISSUE TITLE
Changing "Day Starts" in Anki's scheduling options affects days reviewed, streaks, etc.

### ISSUE THREAD

**Issue by ohotdog** [glutanimate/review-heatmap#44]
#### Problem description
The old "day start" time in my configuration of Anki was 8am, I changed it 10am and noticed my streak was no longer what it was before, and that many of the days in the heatmap had been affected. It seems to me that changing the day start to a time later than it was set to before (i.e. 8am to 10am) causes the heatmap to no longer recognize reviews that took place before the newly set time (so any reviews that took place before 10am on any of the days I had done reviews in the past, in my case)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```
Version: 2.0.47
Qt 4.8.1 PyQt 4.9.1
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Linux 
- version: x86_64 Linux 5.2.1-arch1-1-ARCH

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
Batch_Note_Editing
PassFail_JP
Review Heatmap
morphman
jp
ResetEZ
No_Penalties_or_Boosting
Creat_Copy_of_Selected_Cards

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi. Thanks for the report.

Review Heatmap takes the daily cut-off into consideration when determining which days reviews took pace on. As a result, changing the cut-off can shift reviews around between days, and so you might end up with gap days that you would not have had before.

Unfortunately there is no way to address that as Anki does not record the time zone or daily cut off under which specific reviews took place.

So this is more of a case of "works as expected", I'm afraid.
