### ISSUE TITLE
"Failed to Load" Error

### ISSUE THREAD

**Issue by damronatron** [glutanimate/review-heatmap#45]
#### Problem description

*I installed heat-maps manually but it won't load. I get a "failed to load" message when I open anki. I can see the review-heat map addon on my addons page. I have all the same addons and set up on my Dell Laptop, but heat map works fine on my Dell (the error is happening on my MacBook Pro). 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: MacOS Mojave 10.14.6
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/54161626/63138683-fd7cd500-bfa0-11e9-8d06-ef288deff12e.png)
![image](https://user-images.githubusercontent.com/54161626/63138693-040b4c80-bfa1-11e9-857f-869c52bbf51e.png)

#### Error message (if any)

*An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'review_heatmap':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/Users/ethandamron/Library/Application Support/Anki2/addons21/review_heatmap/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/ethandamron/Library/Application Support/Anki2/addons21/review_heatmap/main.py", line 40, in <module>
    from .gui.options import initializeOptions
  File "/Users/ethandamron/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 46, in <module>
    from ..libaddon.gui.dialog_options import OptionsDialog
  File "/Users/ethandamron/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 44, in <module>
    from ..platform import PLATFORM
ImportError: cannot import name 'PLATFORM'

```python

```

**Comment by glutanimate** [comment]
Hi. It looks like your machine is affected by a bug in Anki's current release (#43). There is a beta release of Anki available that should fix the problem. Please see the discussion here for more info: https://github.com/glutanimate/review-heatmap/issues/43#issuecomment-507514023
