### ISSUE TITLE
How can I add this add-on in MacOS?

### ISSUE THREAD

**Issue by AaronWrdo** [glutanimate/review-heatmap#47]
#### Checklist

 - [ * ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [*] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [*] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

I've downloaded the ".ankiaddon" file and checked this instruction for manual installation for Anki 2.1.
https://github.com/glutanimate/review-heatmap#manual-installation-

The problem is, the video summary only gives the procedure for Win 10, while I'm using MacOS. I tried to drag the file to add-on window but nothing happened.

**Comment by glutanimate** [comment]
I mean, it's the same for all platforms (the GIFin the README was actually recorded on Linux). Here's how it looks like on macOS:

![Screencast_2019-09-11 14-49 mp4](https://user-images.githubusercontent.com/5459332/64698753-bf8da680-d4a3-11e9-9348-070bbef27592.gif)


Did you make sure to update Anki to the latest release, as it says in [step 1](https://github.com/glutanimate/review-heatmap#manual-installation-)

> Make sure you have the [latest version](https://apps.ankiweb.net/#download) of Anki 2.1 installed. Earlier releases (e.g. found in various Linux distros) do not support `.ankiaddon` packages.

**Comment by AaronWrdo** [comment]
> I mean, it's the same for all platforms (the GIF in the README was actually recorded on Linux). Here's how it looks like on macOS:
> 
> ![Screencast_2019-09-11 14-49 mp4](https://user-images.githubusercontent.com/5459332/64698753-bf8da680-d4a3-11e9-9348-070bbef27592.gif)
> 
> Did you make sure to update Anki to the latest release, as it says in [step 1](https://github.com/glutanimate/review-heatmap#manual-installation-)
> 
> > Make sure you have the [latest version](https://apps.ankiweb.net/#download) of Anki 2.1 installed. Earlier releases (e.g. found in various Linux distros) do not support `.ankiaddon` packages.

Sorry I didn't check my Anki version!
For unknown reason, the download speed of Ankiweb is very slow (about 5 ~ 6kb/s) so I often skip updating it.
It's 2.1.8 before and I updated to 2.1.15 today and it worked.
Thank you for your help!
(And sorry if I wasted your time)
