### ISSUE TITLE
Days with reviews being marked as empty

### ISSUE THREAD

**Issue by Aleytia** [glutanimate/review-heatmap#49]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Recently I noticed that there has been a day where I have done 100+ reviews, but the Review Heatmap seems to think I didn't review at all on that day. I looked into the card histories and they are showing that I did a review on the blank day (November 15th in the screenshot below), but the heatmap seems to think otherwise:

![anki_2019-11-18_23-49-51](https://user-images.githubusercontent.com/6107544/69127177-9fa7cf80-0a5e-11ea-907f-5eebc99be95f.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki. (Tried this, nothing changed)
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Add-ons:

True Retention by Card Maturity
Review Heatmap
```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows 10 and MacOS Catalina
- version: ^

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/6107544/69127385-06c58400-0a5f-11ea-84e4-a26ab8a99a8c.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi! Thanks for the detailed report.

A couple quick follow-up questions that might help debugging this:

- Which timezone are you in, if I may ask?
- What is your "Next day starts at" setting set to? (Should be located in your Anki preferences under Tools → Preferences → Basic tab)

Thanks in advance!

**Comment by Aleytia** [comment]
Hey! Looks like it was a next day setting/sync error - thanks! 

Apparently my desktop clients on Windows and Mac OS seem to be set to 11 am, but for some reason AnkiDroid was set to 10 am that day (despite being 11 am otherwise), so all my reviews occurred at 10:25 AM, and I finished the reviews before 11 am. Looks like all the other gaps in my reviews are caused by the same review time next day setting inconsistency too.

Thanks again!
