### ISSUE TITLE
(very likely an Anki issue) Problems after moving between time zones

### ISSUE THREAD

**Issue by StefanDesu** [glutanimate/review-heatmap#5]
Hi,

I just discovered your plugin and decided to test it out. I noticed that there are a couple of days in 2017 that say "no reviews" although I actually have done all my reviews every day. Usually for those days, the previous day has more than the average amount of reviews, suggesting that the reviews done on the missing days counted for the previous day. This makes sense because I lived in Japan during that time and usually did my reviews somewhat early in the morning. With an 7/8 hour time difference to Germany (where I live now), and assuming I did not do early reviews the following day, it could explain the missing days.

This is very likely an issue with Anki. Time zone information is not saved anywhere in the review data, and other people [have experienced a similar issue when moving between time zones](https://www.reddit.com/r/languagelearning/comments/5obc5t/anki_every_day_for_4_years_straight/). The only difference for me compared to this plugin is that Anki itself only shows one missing day (the day I flew back to Germany where Anki made me do two days of reviews in a single day and then marked one day as missing, really weird), while the plugin shows a couple of missing days.

I can also imagine that the "day reset time" (which you can configure yourself) is an additional issue when it's not set to midnight.

My question now is: Do you think there is any way of fixing this? I don't think this is anything for you to fix in the plugin, but rather about me manually adjusting the review times of those done while in Japan. Do you think it would work to write a little Python script that does this adjusting directly in the Anki database? I could specify which interval has to be adjusted in which way (e.g. from 8 September 2016 to 28 September 2017 adjust the review timestamps by x hours).

I'm not sure if this is actually worth the time, but I really like your plugin and it would be cool to see the actual results. Doing a fix like this might also correct the day that Anki claims is missing (or I could manually fix it in the same way).

Here is a screenshot of my heat map, by the way:
![screen shot 2017-08-17 at 09 44 33](https://user-images.githubusercontent.com/3275148/29401752-bf29d61a-8332-11e7-995d-73cb0b2c8caa.png)

Thanks in advance for your input!

**Comment by glutanimate** [comment]
Hi,

this really does sound like a time-zone related issue in Anki. Review Heatmap should just follow suit with Anki's timestamps and day cutoff settings.

At the same time I am a bit surprised that Anki's calculation differs from what the add-on is showing. Not too sure what's going on there. It could very well be a small bug in the add-on that only manifests itself on going through different time-zones. It might also be related to [this report](https://anki.tenderapp.com/discussions/add-ons/8707-review-heatmap-official-thread#comment_42460652). I honestly don't remember if I ever fixed this.

There are a lot of other projects I'm swamped with right now, so I probably won't be able to investigate this for a while, but I'd more than happy to accept a PR if you find a way to address this.

Adjusting the revlog timestamps manually would be a good workaround for now. Personally I would just try to ignore these inconsistencies, but I can understand how this could be very discouraging if you had been carefully curating a review streak (great job on that, btw!)

**Comment by glutanimate** [comment]
So I've just pushed a commit that factors in the daily reset time of your collection when calculating the heatmap data. Could you give this a try, please, and let me know if it changes anything? Just replace your local copy of [`main.py`](https://github.com/glutanimate/review-heatmap/blob/master/review_heatmap/main.py) and you should be set.

**Comment by StefanDesu** [comment]
> So I've just pushed a commit that factors in the daily reset time of your collection when calculating the heatmap data. Could you give this a try please and let me know if it changes anything? Just replace your local copy of main.py and you should be set.

I replaced the main.py and nothing has changed, BUT thinking about this again, I didn't closely follow the day stats back when I switched time zones, so I probably didn't notice that even more days stopped counting. In fact, manually comparing the missing days in the heat map and the missing days in the 1 year statistic, I end up at the same number (29), so your plugin seems to be working correctly.

I guess the issue is a combination of a time zone change and the change in the daily reset time (I had to change it as well because it moved with the time zone). I don't think Anki keeps a history of those either, so there's no real way of fixing this.

> Adjusting the revlog timestamps manually would be a good workaround for now.

I have a few exams coming up, but after those I might look into this. Maybe this can be made into its own plugin, like a time zone changer. I guess testing will be quite difficult though.

> (great job on that, btw!)

Thanks! I'm very proud of this. I started a few days after coming to Japan in September last year with the motivation to catch up on kanji and vocabulary. In our dormitory I was known as THE guy who always finishes his Anki no matter what. To be honest, there were times when I overdid it, doing more than three hours of Anki on a normal weekday with classes and homework. But I noticed it early enough to stop the new cards for a while and let the reviews go down.

**Comment by glutanimate** [comment]
Hey Stefan,

so it looks like I've completely missed your message on this. Sorry about that!

Thanks for testing the commit so diligently. Although it would have been nice if it had fixed the problem completely, I'm still relieved to hear that this is an issue with Anki rather than the add-on.

I don't know if you've had the chance to deal with the timestamps over the past month, but you might have some success with reporting this issue on the [Anki support forums](https://anki.tenderapp.com/discussions/ankidesktop). As you've said, this will most likely not be the first report, but with Anki 2.1 being worked on quite intensively right now, this might be the best time to get a fix for this implemented.

In any case, I wish you good luck with your exams – if any of them are still due – and all of your future Anki-ing. If I ever need an impressive new screenshot for my add-on I'll know who to call!
