### ISSUE TITLE
Anki displays this message :

### ISSUE THREAD

**Issue by charliebobjosh** [glutanimate/review-heatmap#53]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Anki showed an error message before booting
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

![image](https://user-images.githubusercontent.com/47647715/70693926-b8eb1700-1cbe-11ea-9a31-ec922dd90b17.png)

```python

```

**Comment by glutanimate** [comment]
Hey Charlie,

Unfortunately the error message is cut off, but judging by the text so far, this is likely an unrelated issue in Anki or a different add-on. Because Review Heatmap modifies many parts of Anki, it has the unfortunate habit of appearing in many unrelated error messages as sort of a passer-by.

Closing this issue for now, but if you run into the same error again and/or still have the original complete message, please feel free to post it here and reopen the issue report.

Thanks!
