### ISSUE TITLE
Heatmap stuck at 1 year

### ISSUE THREAD

**Issue by kyubae** [glutanimate/review-heatmap#54]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I've done my reps for well over a year in a row now and no matter what I do my current and longest streaks are stuck at 365, when I do my reps for the day they shift to 366 however the next day both will be back to 365. I'd like to be able to track my longest and current streak accurately. Is this a bug or an inherent limitation with Anki? 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

OS: Debian Testing
##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Version 2.1.9 (ae67c976)
Qt 5.12.1 PyQt 5.11.3
```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi! Thanks for the report. What is your history limit set at in the add-on's options (under Settings → Fine Tuning)? If it's set to 365 days, please try turning it all the way down until it says "No limit" (or enter 0, which is the equivalent value). Does your streak update properly now?

**Comment by kyubae** [comment]
Hi, Yeah thanks setting the history limit to "No limit" fixed the issue, my bad, I couldn't find that setting on my own. I honestly do not see a point in their being a default limit, perhaps you should consider setting "No Limit" as the default?

**Comment by glutanimate** [comment]
Sorry for the late reply. Happy to hear that changing the setting fixed things! "No Limit" is the default in recent versions, but it used to be that heatmap calculation was quite performance-intensive, and so it was set to 1 year as a default. That setting likely persisted over to the new release in your case.

Either way, happy we tackled this!
