### ISSUE TITLE
Why do you host the CSS online instead of having the user download it along with the add-on?

### ISSUE THREAD

**Issue by nickdvlpr** [glutanimate/review-heatmap#57]
I'm just wondering about your reasoning because I'm considering doing the same for my add-ons. Is it so that you can "update" the appearance of the add-on without requiring the user to download an update on AnkiWeb?

Specifically referring to this file: **_review-heatmap/resources/web/review-heatmap.css_**

**Thanks!**

**Comment by glutanimate** [comment]
Hey! Sorry, busy week. The files under /resources are actually loaded into Qt's resource and then accessed from there instead of reading from the disk directly. This was mostly a concession to trouble with unicode paths in Anki 2.0, and security policies against local filesystem access in early Anki 2.1 releases. Nowadays it's simple enough to load CSS & JS in directly, and in the next major release that's the approach Review Heatmap will also likely be taking. Hope that explains things!

**Comment by glutanimate** [comment]
Closing this for now, but if you have any follow-up questions feel free to shoot away.

**Comment by nickdvlpr** [comment]
Thanks for the info! Would there be a good way to change the colors of Review Heatmap for my own personal use? Specifically the grays used for the background of the boxes.

**Comment by glutanimate** [comment]
There is no API or anything, but you can just inject your own CSS  in the respective views and overrule the add-on's default CSS: https://github.com/glutanimate/review-heatmap/blob/master/resources/web/review-heatmap.css#L222

Injecting your own CSS should be fairly easy if you use the new webhooks in Anki 2.1.21 and up.

**Comment by AustinHasten** [comment]
For anyone who comes across this, I overwrote a theme with this:
```
from aqt import mw, gui_hooks
from aqt.utils import showInfo, showText

def test(web_content, context):
    addon_package = mw.addonManager.addonFromModule(__name__)
    
    web_content.css.append(
        f"/_addons/{addon_package}/web/my-addon.css"
    )

mw.addonManager.setWebExports(__name__, r"web/.*\.css")
gui_hooks.webview_will_set_content.append(test)
```

Then stick a "my-addon.css" in the addon's web folder. This is what mine looks like:
```
.night_mode .rh-theme-flame .cal-heatmap-container .q11{
    fill: #645484 !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q12{
    fill: #6e5b91 !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q13{
    fill: #77629e !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q14{
    fill: #8169ab !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q15{
    fill: #8b70b8 !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q16{
    fill: #9577c5 !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q17{
    fill: #9f7ed2 !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q18{
    fill: #a985df !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q19{
    fill: #b38cec !important;
}
.night_mode .rh-theme-flame .cal-heatmap-container .q20{
    fill: #bd93f9 !important;
}


.night_mode .rh-theme-flame .rh-col11{
    color: #645484 !important;
}
.night_mode .rh-theme-flame .rh-col12{
    color: #6e5b91 !important;
}
.night_mode .rh-theme-flame .rh-col13{
    color: #77629e !important;
}
.night_mode .rh-theme-flame .rh-col14{
    color: #8169ab !important;
}
.night_mode .rh-theme-flame .rh-col15{
    color: #8b70b8 !important;
}
.night_mode .rh-theme-flame .rh-col16{
    color: #9577c5 !important;
}
.night_mode .rh-theme-flame .rh-col17{
    color: #9f7ed2 !important;
}
.night_mode .rh-theme-flame .rh-col18{
    color: #a985df !important;
}
.night_mode .rh-theme-flame .rh-col19{
    color: #b38cec !important;
}
.night_mode .rh-theme-flame .rh-col20{
    color: #bd93f9 !important;
}
```

I chose flame, you could overwrite any others by changing .rh-theme-flame.
