### ISSUE TITLE
Cant drag and drop the *.ankiaddon file into the addon- field.

### ISSUE THREAD

**Issue by Sunburst275** [glutanimate/review-heatmap#58]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

*Like in the title, I cant drag and drop the *.ankiaddon file into the addon- field. I just gives me a "stop"- sign. Also unpacking and dragging it into the add-on folder wont help. After start- up (Anki) it says something along the lines of: "Found no member of review_heatmap" and so on. How to fix this?*

**Comment by glutanimate** [comment]
Hi Sunburst,

Please update to the latest version of Anki and try again: https://apps.ankiweb.net/#download

**Comment by Sunburst275** [comment]
> Hi Sunburst,
> 
> Please update to the latest version of Anki and try again: https://apps.ankiweb.net/#download

Thank you.  I looked at the "About" tab and it said that it was the latest version.
I just reinstalled it and now it works.

Danke dir!

**Comment by glutanimate** [comment]
Happy to hear everything's working now!

Keine Ursache :)
