### ISSUE TITLE
Support for Anki 2.1

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/review-heatmap#6]
subj. thanks in advance. love it.

**Comment by glutanimate** [comment]
In due time. Currently waiting for Anki 2.1 to stabilize a bit further. I would also like to fix some performance issues before implementing 2.1 support.

**Comment by glutanimate** [comment]
The latest master branch now support Anki 2.1 (0f31e654bbee11573f9b200da41376f4608e9347). You can give it a try if you'd like by manually installing the add-on. I can't guarantee that the add-on will remain compatible with all future 2.1 beta releases though. This is more of a one-off conversion in preparation of the eventual stable release. Maintaining 2.1 support across potentially fluctuating beta releases would cost too much time for me right now.

**Comment by busfahr3r** [comment]
Hi, any updates on 2.1 functioanlity? Really appreciate your addon and all the work you have put into!

**Comment by glutanimate** [comment]
Thanks for the kind words! Still working on the 2.1 release. This will be the first major release in a year, so it's also going to address a number of other outstanding issues and feature requests. You can take a sneak peek at the next release on my [Patreon](https://www.patreon.com/posts/review-heatmap-7-20721858) if you don't mind the paywall. I don't want to give any concrete ETA, as things can always get in the way, but it should be soon (rather this than the next month).
