### ISSUE TITLE
What's the latest way of installing the addon?

### ISSUE THREAD

**Issue by turquoise-turtle** [glutanimate/review-heatmap#65]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've checked if anyone else asked this question before by looking through the issue reports.

#### What's the latest way of installing the addon for Anki 2.1.x?

I saw in the readme that the manual installation method is to download the latest release from the releases tab. However, the most recent release is from 1.5 years ago, which is confusing since I can see that there are "66 commits to master since this release".

Is that the most recent working version for Anki 2.1.x? Or am I meant to compile the addon myself? 
[https://ankiweb.net/shared/info/1771074083](https://ankiweb.net/shared/info/1771074083) says it hasn't been updated since 2017, and is only for Anki 2.0.x.

**Comment by arivogel** [comment]
I just installed this add-on for (my Anki version is 2.1.22).  It was actually the first add-on I've used so I was also unsure how to install, and thought I could help if you haven't found the answer yet.

In the anki application, go to the 'Tools' Menu, and click 'Add-ons'.  This will take you to the add-on menu which looks roughly like this:

![anki-addon](https://user-images.githubusercontent.com/7495261/80931927-c8542500-8d71-11ea-9856-c243194fd5a9.PNG)

That top button on the right 'Get Add-ons'  will take you to a form where you can input the following code: 1722241614

I got that code from https://ankiweb.net/shared/info/1722241614

You can also use the 'Browse Add-ons' button to find other add-ons you may like.

Hope this helps.

**Comment by jldugger** [comment]
Note that https://ankiweb.net/shared/info/1722241614 is not directly associated with this repo and hasn't been updated since 2019.  @glutanimate what's the plan to resolve that? Seems like it it won't be on ankiweb until 1.0, but the beta was a few years ago. Are there any blockers filed stopping a 1.0 release? 

Beyond that, has there been any discussion with @dae regarding doppleganger plugins?

**Comment by glutanimate** [comment]
Hey guys, two years later, but I'm happy to say that the add-on is now finally available directly via AnkiWeb (starting with the just released v1.0.0): https://ankiweb.net/shared/info/1771074083

As for the duplicate listings, I will see if I can reach out to the uploaders. It would definitely be nice to resolve this confusion, especially given that people downloading older versions from these listings has unfortunately contributed to many support requests over the years.
