### ISSUE TITLE
ModuleNotFoundError on startup

### ISSUE THREAD

**Issue by pesua** [glutanimate/review-heatmap#66]
#### Problem description

I've just installed the fresh version of anki and heatmap built with addon builder and I'm seeing the error during the startup.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

```
Anki 2.1.16 (dev) Python 3.6.9 Qt 5.9.5 PyQt 5.10.1
Platform: Linux
Flags: frz=False ao=True sv=1

Add-ons:

Review Heatmap
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Ubuntu
- version: 18.04.4 LTS

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

```python
Traceback (most recent call last):
  File "/snap/anki-woodrow/20/lib/python3.6/site-packages/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/pesua/snap/anki-woodrow/20/.local/share/Anki2/addons21/review_heatmap/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/home/pesua/snap/anki-woodrow/20/.local/share/Anki2/addons21/review_heatmap/main.py", line 40, in <module>
    from .gui.options import initializeOptions
  File "/home/pesua/snap/anki-woodrow/20/.local/share/Anki2/addons21/review_heatmap/gui/options.py", line 51, in <module>
    from .forms import options as qtform_options
  File "/home/pesua/snap/anki-woodrow/20/.local/share/Anki2/addons21/review_heatmap/gui/forms/__init__.py", line 39, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'review_heatmap.gui.forms.anki21'
```

**Comment by glutanimate** [comment]
Hi pesua,

It seems like the UI build did not complete correctly. Are you sure pyuic5 and pyrcc5 are in your PATH? As mentioned in the README, you'll need an Anki development environment set up for `aab` to work correctly (with the pyqt UI build tools being part of that).

Please see this earlier issue for more information: https://github.com/glutanimate/anki-addon-builder/issues/4#issuecomment-500143923

Also, you're using a very old (and moreover dev) version of Anki. I would highly recommend switching to the official builds instead ot the snap you're currently using: https://apps.ankiweb.net/#download

Closing this as it's an issue with the build environment.
