### ISSUE TITLE
Review Heatmap

### ISSUE THREAD

**Issue by idkei** [glutanimate/review-heatmap#78]
#### Problem description

Hi I've just got started with anki and found this addon through youtube videos. Great addon you made there! 
It installs and works fine but when I try to change the colour or add exclude folders 
i get this error msg.

Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.12.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-09 21:46:02
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/nebula/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_basic.py", line 93, in accept
    self._onAccept()
  File "/Users/nebula/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "/Users/nebula/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 216, in save
    saver(self._config[name])
  File "/Users/nebula/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki/config.py", line 60, in __setitem__
  File "anki/config.py", line 36, in set
  File "anki/rsbackend.py", line 591, in set_config_json
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

any help with this?

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there!

Thanks for the detailed bug report. It looks like you're using an outdated version of the add-on. Please update to the latest release which is currently available under this link: https://github.com/glutanimate/review-heatmap/releases/download/v1.0.0-beta.1/review-heatmap-v1.0.0-beta.1-anki21.ankiaddon

That should fix the issue you were experiencing.

In the future please check with the download link at the top here: https://ankiweb.net/shared/info/1771074083

That will always point to the latest release.

Hope that helps!

**Comment by idkei** [comment]
cool! thanks for the note!
