### ISSUE TITLE
Review Heatmap not showing up on Anki home screen 

### ISSUE THREAD

**Issue by le-bon-bock** [glutanimate/review-heatmap#80]
#### Problem description

Running Review Heatmap v1.0.0-beta.1 

My Heatmap does not display on the home screen on opening Anki. 

If I click on a square it takes me to browser and when I return to home screen the heatmap is displayed as normal. 

If I then click on a deck and start working, when I return to the home screen the heatmap has disappeared again.

 
<img width="762" alt="Screenshot 2020-06-16 at 17 59 22" src="https://user-images.githubusercontent.com/67017155/84804896-51aa7880-affb-11ea-9e2a-8373715b4e28.png">
<img width="801" alt="Screenshot 2020-06-16 at 17 59 38" src="https://user-images.githubusercontent.com/67017155/84804904-53743c00-affb-11ea-835d-4d777b6a4f7b.png">
<img width="772" alt="Screenshot 2020-06-16 at 18 00 21" src="https://user-images.githubusercontent.com/67017155/84804906-540cd280-affb-11ea-887e-09c9fde0c6e7.png">

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [yes] I've restarted Anki to see if it helps
 - [yes] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [yes] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [yes ] I've tried to disable other add-ons to see if there are any interactions present
 - [no] My issue disappears when I hold shift while starting Anki.
 - [yes] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
    Platform: Mac 10.15.4
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-06-16 16:06:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Review Heatmap ['review_heatmap', 2020-04-30T14:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2020-04-27T21:52, 'None', mod]
    Advanced Browser ['874215009', 2020-02-20T22:39, 'None', '']
    Answer Confirmation for 21 ['1354051622', 2020-05-15T16:05, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-06-11T13:32, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2020-03-14T01:20, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-05-15T11:31, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T03:21, 'None', '']
    Life Drain ['715575551', 2020-06-06T09:47, 'None', '']
    More Overview Stats 21 ['738807903', 2020-01-22T12:51, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T17:32, 'None', '']
    Resize images in editor ['1103084694', 2020-05-18T20:29, 'None', mod]
    Symbols As You Type ['2040501954', 2020-04-30T15:32, 'None', '']
    True Retention ['613684242', 2017-11-19T20:43, 'None', '']
    extended editor for field for tables searchreplace  ['805891399', 2020-06-08T10:35, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by JustOneCarb** [comment]
Hey, I don't know how to help but just wanted to say I have the exact same problem and it started today (or at least I just noticed it for the first time today).  I didn't even realize I could reset it by clicking a square, but you're right, that works for me to restore it too, and it does disappear again when I click a deck and go back.  And the individual decks still work fine, it's just my overall collection on the main screen that has no color.

**Comment by le-bon-bock** [comment]
Started working again! Weird.

**Comment by glutanimate** [comment]
Hi guys,

Thanks for the reports! Please see my reply here: https://github.com/glutanimate/review-heatmap/issues/70#issuecomment-657229570

Your collections likely contain cards whose due dates were somehow set to an invalid date by a third-party add-on / and or a bug in Anki, so you might want to see if you can track down what caused this.

The comment I linked above also contains a test release of Review Heatmap that ignores invalid cards like this, thus making the heatmap work properlay again.
