### ISSUE TITLE
New Linux user. Click and Drag doesn't work

### ISSUE THREAD

**Issue by diatomm** [glutanimate/review-heatmap#81]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.

#### Diatom's Question
Greeting!
I think this is just because I am a new linux user. I am unable to do the click and drag with the *".addon"* file as demonstrated in the gifs. I suspected this would be an issue based on what I already understand about linux. If any linux users could help bring me up to speed I would be super greatful!
Cheers,
-D

**Comment by glutanimate** [comment]
Hi diatomm,

Generally the issue with Anki on Linux is that a lot of Linux distributions ship outdated Anki builds, which can result in more recent features like drag-and-drop add-on installation not working.

My recommendation would be to check under Help → About which Anki version your using. It will likely be below 2.1.10 (that's the point release where .ankiaddon support was introduced).

If so, I would suggest uninstalling the distro-provided Anki version and installing one of the official builds here: https://apps.ankiweb.net/#download

(I would opt for the stable release)

Hope that helps!

Closing this for now as it does not pertain to Review Heatmap in particular. But feel free to let me know if the steps above don't work.

**Comment by glutanimate** [comment]
Here's more info on the Anki packaging situation on Linux, BTW: https://anki.tenderapp.com/kb/anki-ecosystem/third-party-linux-packages-and-source-builds-are-not-supported

**Comment by diatomm** [comment]
Thanks Glutimate,
Defs on an old version. Glad you could point that out to me. Thanks for all the work you do for the community! I can't do reviews without the heatmap anymore!
