### ISSUE TITLE
Error When Trying to Customize

### ISSUE THREAD

**Issue by coloredtwizzler** [glutanimate/review-heatmap#87]
#### Problem description

Error occurs whenever I try to change color scheme/timeline option and press ok. Could this be because of the new updates and not due to one of the addons? Thank you.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-11 19:43:14
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/temitayoadanlawo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_basic.py", line 93, in accept
    self._onAccept()
  File "/Users/temitayoadanlawo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "/Users/temitayoadanlawo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 216, in save
    saver(self._config[name])
  File "/Users/temitayoadanlawo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki/config.py", line 64, in __setitem__
  File "anki/config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict


```

**Comment by glutanimate** [comment]
You are using an outdated version of the add-on. Please update to the latest release: https://ankiweb.net/shared/info/1771074083 (download link at the top).
