### ISSUE TITLE
Seems like 2.1.x version conflicts with the «Night Mode» addon.

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/review-heatmap#9]
I don't actually know, if it's possible to fix it, but both of these addons are great.

— https://github.com/krassowski/Anki-Night-Mode

2.0.x was ok. Thanks.

**Comment by glutanimate** [comment]
Thanks for letting me know, July. It seems @krassowski has recently released a completely overhauled version of the night mode add-on for 2.1. Does the issue still persist with that?

**Comment by krassowski** [comment]
@JulyMorning what is the exact problem you experience?

@glutanimate we both use `Overview._body` ([stylers.py#L230](https://github.com/krassowski/Anki-Night-Mode/blob/master/night_mode/stylers.py#L230) in Night Mode). I just append styles to the existing body while your addon (If I understand correctly) attempts to replace it with a hardcoded value altogether  (see [main.py#L239](https://github.com/glutanimate/review-heatmap/blob/master/review_heatmap/main.py#L239)).

I am not sure why, but when I tried it in 2.1 Beta 16 both add-ons worked well. I did not use the heatmap before (so I may not know about certain, possibly lacking features) but both deck browser and overview screens have their heatmaps and are styled nicely.

PS. A minor issue is some glittering when going back from overview to deck browser. Let me know if you spot what's causing it.

Cheers!

**Comment by glutanimate** [comment]
@krassowski Thanks for chiming in and investigating this! Yep, the add-on replaces the overview body altogether. As far as I remember this was necessary to get the layout right, but I will see if I can find a different way to handle this when I find the time.

Not sure why the add-ons would work in some instances, but not in others. Perhaps a race condition where the result varies depending on which add-on is loaded first by Anki? The module loading order seems to depend on the path of Anki's add-on directory which is user-specific of course.

**Comment by krassowski** [comment]
Concurrency may be the problem here.

What I found out recently is that when review-heatmap is enabled it effectively prevents night-mode to style counts on the overview screen:

![screenshot from 2017-10-14 12-23-20](https://user-images.githubusercontent.com/5832902/31575630-61e12c56-b0d2-11e7-8c32-c69f2a111026.png)
![screenshot from 2017-10-14 12-22-49](https://user-images.githubusercontent.com/5832902/31575631-621178de-b0d2-11e7-99f4-25a5c5118b34.png)

That's not a big issue though.

**Comment by rptr87** [comment]
@JulyMorning @krassowski  

Could you share steps to test HeatMap with Anki 2.1. 
I placed py script into Anki21 addon folders but it does not seem to work.

**Comment by glutanimate** [comment]
@rptr87 @salthepal @HongKTruong The repo is currently in somewhat of a transitional state, but I will let you guys know once the beta for the v0.7.0 release is ready (which will bring 2.1 support, among other things). At that point I will also try to look into potential compatibility issues with Night Mode again.

**Comment by glutanimate** [comment]
Hey everyone,

I'm happy to say that the [first beta release of v0.7.0](https://github.com/glutanimate/review-heatmap/releases) is finally here!

Among other things it comes with full night mode support (including a series of themes specifically crafted for night mode). If you could give it a try and report back about your experience I'd really appreciate that. Please make sure to upgrade [Night Mode](https://ankiweb.net/shared/info/1496166067) to the latest release if you do, as it packs some changes that Review Heatmap depends on.

Major shout-out to @krassowski for shouldering the work on Night Mode's end!

**Comment by glutanimate** [comment]
Also: I'd love to hear you guys' thoughts on the night themes. For most of them I inverted the color assignment compared to their day counterparts. I feel like this works well for some themes (e.g. magenta, flame, ice), but as well for others (e.g. olive, lime). But I'm not sure in what direction to take the night versions of the latter. Any kind of feedback would be much appreciated!

**Comment by salthepal** [comment]
Personally I'm a fan of the color inversion, especially for the flame theme.

**Comment by MS3509** [comment]
Not sure what the current status for this is. I do have the most recent version of both, and all works well without any observed issues. I would greatly appreciate the ability to turn off the color inversion, though, as it does become confusing. 

Thanks for a great add-on

**Comment by NilsIrl** [comment]
Anki now has built-in night mode and the night mode addon has been archived. This should probably be closed.

**Comment by glutanimate** [comment]
@NilsIrl :+1:
