### ISSUE TITLE
[Review Heatmap] Unable to change from continuous to yearly overview permanently 

### ISSUE THREAD

**Issue by jeremyalexx** [glutanimate/review-heatmap#90]
## Which add-on is affected?

[Review Heatmap]
[Review Heatmap] Unable to change from continuous to yearly overview permanently 

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [X] In case of a bug: Have you tried restarting Anki?
- [X] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X] Did you check the add-on description on AnkiWeb for known issues?
- [ ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I have my Review Heatmap set as "yearly overview" and would like to change it to "continuous". This is an inbuilt feature. 

[ What were you doing when the problem occurred? ]
Attempting to change the heatmap display.

1. [ First step ]
Cliciking on settings and optint to change the 
<img width="383" alt="S1 - action" src="https://user-images.githubusercontent.com/68852840/88600236-de415f80-d0ac-11ea-9931-f85a5993fee1.png">
2. [ Second step ] - the error
<img width="630" alt="S2 - error" src="https://user-images.githubusercontent.com/68852840/88600245-e1d4e680-d0ac-11ea-89c7-78239fc52fc9.png">
3. [ Third step]
By selecting cancel and the opting to  'sync' causes the heatmap to change to the continuous display. 
However, this is not permanent and reverts to the prior setting upon restarting Anki. 
<img width="767" alt="S3 - post sync" src="https://user-images.githubusercontent.com/68852840/88600249-e3061380-d0ac-11ea-98e3-8ed378d99e14.png">

## How can we reproduce the problem?
As above: 
Error string below:

Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-27 19:20:48
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_basic.py", line 93, in accept
    self._onAccept()
  File "/Users/alex/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "/Users/alex/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 216, in save
    saver(self._config[name])
  File "/Users/alex/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki/config.py", line 64, in __setitem__
  File "anki/config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

**Expected behavior:** [ What you expected to happen ]
The review heatmap display to change to continuous. 

**Actual behavior:** [ What actually happened ]
Described above.

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]
Yes, this happens when changing to the "other option" in review heatmap irrespective of what you have set currently. 

## Version information
**Anki**
Version 2.1.28 (7d8818f8)
Python 3.8.0 Qt 5.15.0 PyQt 5.15.0

**System**

- Operating system:  MacOs
- Version: Catalina 10.15.6

**Comment by glutanimate** [comment]
Hi Jeremy,

Thanks for the super-detailed bug report! Really appreciate it.

It looks like your're using an outdated version of Review Heatmap. Updating to the latest version should fix things. You can grab the latest download directly by clicking on the link at the top of the page here: https://ankiweb.net/shared/info/1771074083

(In the (near) future you'll also be able to install Review Heatmap normally like any other add-on by copying its code, but for now the manual download is the way to go).

Hope that helps!
