### ISSUE TITLE
No colors shown for days studied

### ISSUE THREAD

**Issue by arkhandir** [glutanimate/review-heatmap#96]
#### Problem description

After starting Anki today, Review Heatmap appeared in its usual form except study days show no colors anymore. There was a one time error message when clicking around in the Review Heatmap options (didn't copy it), since then no error message is shown anymore. I did not change anything regarding my Anki setup for a few days. 

![Bildschirmfoto 2020-09-12 um 15 24 22](https://user-images.githubusercontent.com/1059703/92996483-3b358f80-f50c-11ea-9bf4-64f961dd7819.jpg)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki (nothing shown anymrore)
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.6
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-09-11 22:35:01
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2020-07-25T14:19, 'None', mod]
    Advanced Browser ['874215009', 2020-04-23T00:45, 'None', '']
    AnkiWebView Inspector ['31746032', 2019-05-03T00:43, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2020-09-01T15:59, 'None', '']
    BetterTags ['bettertags', 2020-04-28T17:40, 'None', mod]
    Clickable Tags v11 ['380714095', 2020-03-22T14:56, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T13:37, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T22:01, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    Mini Format Pack ['295889520', 2019-09-26T18:02, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T08:26, 'None', '']
    Resize images in editor ['1103084694', 2020-08-02T15:04, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T22:13, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1103084694 1237621971 1374772155 1436550454 1988760596 266436365 295889520 31746032 380714095 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Auto Markdown ['1030875226', 2019-09-13T21:21, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    BetterSearch ['1052724801', 2020-07-29T00:44, 'None', '']
    External Note Editor for the Browser ['1996266159', 2020-03-31T22:59, 'None', '']
    Ignore accents in browser search ['1924690148', 2020-08-08T14:17, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T14:35, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-09-25T22:52, 'None', '']
    Search and Replace Tags ['138501288', 2019-09-12T12:35, 'None', '']
    True Retention ['613684242', 2019-09-12T00:00, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi arkhandir,

It looks like you're using an older version of the add-on. Updating to the latest release, which you can find linked at the top [here](https://ankiweb.net/shared/info/1771074083), should fix the display issue.

Underlying the problem you're seeing with the missing colors is that some of your cards likely have invalid scheduling data attached to them. This might have happened as a result of a bug in Anki's scheduler or a third-party add-on interfering with things (though not Review Heatmap, as it does not touch your cards' scheduling). To fix the invalid cards, I would highly suggest that you run a database check via Tools → Check Database.

For more information on this issue please also see here: #70
